version: "3"

services:

  db:
    image: postgres:18
    restart: on-failure
    volumes:
      - ./db/data:/var/lib/postgresql
    env_file:
      - ../.env
    
  app:
    build: ../
    ports:
      - 80:80
    restart: on-failure
    volumes:
      - ..:/workspace:cached